sonar.projectKey=SonyaNazaryshyna_project2_refactoring
sonar.organization=sonyanazaryshyna
sonar.host.url=https://sonarcloud.io
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage-full.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S4502
sonar.issue.ignore.multicriteria.e1.resourceKey=src/presentation/controllers/**
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/staticfiles/**,**/frontend/**,**/static/**,**/templates/**
sonar.coverage.exclusions=**/migrations/**,**/settings.py,**/wsgi.py,**/manage.py,**/celery_app.py
sonar.sourceEncoding=UTF-8
